apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-page-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-page-app
  template:
    metadata:
      labels:
        app: main-page-app
    spec:
      containers:
        - name: main-page-app
          image: 1t1scool/main-page-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0" # Позволяет K8s достучаться до пода
          resources:
            requests:
              memory: "256Mi" # Увеличил базу
              cpu: "200m"
            limits:
              memory: "1Gi" # Запас для обработки 35 картинок
              cpu: "1000m" # 1 целое ядро для быстрой работы SSR
          livenessProbe:
            httpGet:
              path: / # Изменил на корень, так надежнее
              port: 3000
            initialDelaySeconds: 30 # Даем больше времени на холодный старт
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
