apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-page
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: main-page
                port:
                  number: 80
