apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-page
  namespace: default
  annotations:
    # Явно говорим, что этот Ingress для Traefik
    kubernetes.io/ingress.class: "traefik"
    # Подключаем наш редирект (мы его создали в default)
    traefik.ingress.kubernetes.io/router.middlewares: default-force-https@kubernetescrd
spec:
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: main-page
                port:
                  number: 80
  tls:
    - hosts:
        - mmalabugin.ru
      secretName: main-page-tls
