apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-page
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
spec:
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: main-page
                port:
                  number: 80
  tls:
    - hosts:
        - mmalabugin.ru
      secretName: main-page-tls
