apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-page
spec:
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: main-page
                port:
                  number: 80
  tls:
    - hosts:
        - mmalabugin.ru
      secretName: main-page-tls
