apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-page
  namespace: default
  annotations:
    # 1. Говорим, что этот ингресс слушает обе точки
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # 2. Включаем автоматический редирект только для HTTP
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: main-page
                port:
                  number: 80
  tls:
    - hosts:
        - mmalabugin.ru
      secretName: main-page-tls
