apiVersion: v1
kind: Service
metadata:
  name: main-page
  namespace: default
spec:
  selector:
    app: main-page-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
