apiVersion: v1
kind: Service
metadata:
  name: main-page
  namespace: default
spec:
  selector:
    app: main-page-app # Должно совпадать с labels в Deployment
  ports:
    - protocol: TCP
      port: 80 # Порт, по которому к сервису обращаются внутри кластера (и Ingress)
      targetPort: 3000 # Порт самого приложения Next.js внутри контейнера
  type: ClusterIP
